services:
    book-web-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: book-web-app:latest
        container_name: book-web-app
        depends_on:
            postgres:
                condition: service_healthy
            cache:
                condition: service_healthy
        ports:
            - 8080:8080
        networks:
            - app-network
    cache:
        image: redis:latest
        container_name: cache
        healthcheck:
            test: redis-cli ping | grep PONG
            interval: 1s
            timeout: 3s
            retries: 5
        ports:
            - 6379:6379
        networks:
            - app-network
        command: redis-server
    postgres:
        image: postgres:16.2-alpine
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: books_db
        healthcheck:
            test: pg_isready -d books_db -U postgres
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 5s
        ports:
            - 5432:5432
        networks:
            - app-network
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
        name: postgres-data
        driver: local

networks:
    app-network:
        name: app-network
        driver: bridge